# .\fsgim.py
# -*- coding: utf-8 -*-
# PyXB bindings for NM:10e9994e75dfd8231ca84c5e346bb93e6592cf9d
# Generated 2022-06-15 17:44:41.181989 by PyXB version 1.2.6 using Python 3.9.5.final.0
# Namespace urn:X-fsgim:fsgim [xmlns:fsgim]

from __future__ import unicode_literals
import pyxb
import pyxb.binding
import pyxb.binding.saxer
import io
import pyxb.utils.utility
import pyxb.utils.domutils
import sys
import pyxb.utils.six as _six
# Unique identifier for bindings created at the same time
_GenerationUID = pyxb.utils.utility.UniqueIdentifier('urn:uuid:5bda92e2-ecf4-11ec-a32f-ac8247e092b3')

# Version of PyXB used to generate the bindings
_PyXBVersion = '1.2.6'
# Generated bindings are not compatible across PyXB versions
if pyxb.__version__ != _PyXBVersion:
    raise pyxb.PyXBVersionError(_PyXBVersion)

# A holder for module-level binding classes so we can access them from
# inside class definitions where property names may conflict.
_module_typeBindings = pyxb.utils.utility.Object()

# Import bindings for namespaces imported into schema
import _nsgroup as _ImportedBinding__nsgroup

# NOTE: All namespace declarations are reserved within the binding
Namespace = pyxb.namespace.NamespaceForURI('urn:X-fsgim:fsgim', create_if_missing=True)
Namespace.configureCategories(['typeBinding', 'elementBinding'])

def CreateFromDocument (xml_text, default_namespace=None, location_base=None):
    """Parse the given XML and use the document element to create a
    Python instance.

    @param xml_text An XML document.  This should be data (Python 2
    str or Python 3 bytes), or a text (Python 2 unicode or Python 3
    str) in the L{pyxb._InputEncoding} encoding.

    @keyword default_namespace The L{pyxb.Namespace} instance to use as the
    default namespace where there is no default namespace in scope.
    If unspecified or C{None}, the namespace of the module containing
    this function will be used.

    @keyword location_base: An object to be recorded as the base of all
    L{pyxb.utils.utility.Location} instances associated with events and
    objects handled by the parser.  You might pass the URI from which
    the document was obtained.
    """

    if pyxb.XMLStyle_saxer != pyxb._XMLStyle:
        dom = pyxb.utils.domutils.StringToDOM(xml_text)
        return CreateFromDOM(dom.documentElement, default_namespace=default_namespace)
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    saxer = pyxb.binding.saxer.make_parser(fallback_namespace=default_namespace, location_base=location_base)
    handler = saxer.getContentHandler()
    xmld = xml_text
    if isinstance(xmld, _six.text_type):
        xmld = xmld.encode(pyxb._InputEncoding)
    saxer.parse(io.BytesIO(xmld))
    instance = handler.rootObject()
    return instance

def CreateFromDOM (node, default_namespace=None):
    """Create a Python instance from the given DOM node.
    The node tag must correspond to an element declaration in this module.

    @deprecated: Forcing use of DOM interface is unnecessary; use L{CreateFromDocument}."""
    if default_namespace is None:
        default_namespace = Namespace.fallbackNamespace()
    return pyxb.binding.basis.element.AnyCreateFromDOM(node, default_namespace)

from _nsgroup import DemandTarget # {urn:X-fsgim:fsgim}DemandTarget
from _nsgroup import EMPresentData # {urn:X-fsgim:fsgim}EMPresentData
from _nsgroup import PeakPowerData # {urn:X-fsgim:fsgim}PeakPowerData
from _nsgroup import EnvelopeContentsType # {urn:X-fsgim:fsgim}EnvelopeContentsType
from _nsgroup import OptionTypeType # {urn:X-fsgim:fsgim}OptionTypeType
from _nsgroup import PriceBaseType # {urn:X-fsgim:fsgim}PriceBaseType
from _nsgroup import BaseCIM_CombinedVersion # {urn:X-fsgim:fsgim}BaseCIM_CombinedVersion
from _nsgroup import CustomerAgreement # {urn:X-fsgim:fsgim}CustomerAgreement
from _nsgroup import EndDeviceAsset # {urn:X-fsgim:fsgim}EndDeviceAsset
from _nsgroup import EnergyUsageInformation # {urn:X-fsgim:fsgim}EnergyUsageInformation
from _nsgroup import LineItem # {urn:X-fsgim:fsgim}LineItem
from _nsgroup import NAESB_EUI_Version # {urn:X-fsgim:fsgim}NAESB_EUI_Version
from _nsgroup import PositionPoint # {urn:X-fsgim:fsgim}PositionPoint
from _nsgroup import RationalNumber # {urn:X-fsgim:fsgim}RationalNumber
from _nsgroup import ReadingInterharmonic # {urn:X-fsgim:fsgim}ReadingInterharmonic
from _nsgroup import ReadingQuality # {urn:X-fsgim:fsgim}ReadingQuality
from _nsgroup import ReadingType # {urn:X-fsgim:fsgim}ReadingType
from _nsgroup import RoleFlags # {urn:X-fsgim:fsgim}RoleFlags
from _nsgroup import ServiceCategory # {urn:X-fsgim:fsgim}ServiceCategory
from _nsgroup import ServiceDeliveryPoint # {urn:X-fsgim:fsgim}ServiceDeliveryPoint
from _nsgroup import ServiceSupplier # {urn:X-fsgim:fsgim}ServiceSupplier
from _nsgroup import SummaryMeasurement # {urn:X-fsgim:fsgim}SummaryMeasurement
from _nsgroup import TariffProfile # {urn:X-fsgim:fsgim}TariffProfile
from _nsgroup import UnitEnergyPriceType # {urn:X-fsgim:fsgim}UnitEnergyPriceType
from _nsgroup import FSGIMAtomLink # {urn:X-fsgim:fsgim}FSGIMAtomLink
from _nsgroup import FSGIMWeatherAtomLink # {urn:X-fsgim:fsgim}FSGIMWeatherAtomLink
from _nsgroup import DERDatasheetEmissions # {urn:X-fsgim:fsgim}DERDatasheetEmissions
from _nsgroup import SupplyArrayElement # {urn:X-fsgim:fsgim}SupplyArrayElement
from _nsgroup import DateTimeInterval # {urn:X-fsgim:fsgim}DateTimeInterval
from _nsgroup import DstTransitionRule # {urn:X-fsgim:fsgim}DstTransitionRule
from _nsgroup import AttachType # {urn:X-fsgim:fsgim}AttachType
from _nsgroup import AvailabilityType # {urn:X-fsgim:fsgim}AvailabilityType
from _nsgroup import ToleranceValueType # {urn:X-fsgim:fsgim}ToleranceValueType
from _nsgroup import VavailabilityType # {urn:X-fsgim:fsgim}VavailabilityType
from _nsgroup import WeekdaySpecType # {urn:X-fsgim:fsgim}WeekdaySpecType
from _nsgroup import RecurType # {urn:X-fsgim:fsgim}RecurType
from _nsgroup import CurtailmentArrayElement # {urn:X-fsgim:fsgim}CurtailmentArrayElement
from _nsgroup import CurtailmentValueType # {urn:X-fsgim:fsgim}CurtailmentValueType
from _nsgroup import PowerRampSegmentType # {urn:X-fsgim:fsgim}PowerRampSegmentType
from _nsgroup import ConnectionPoint # {urn:X-fsgim:fsgim}ConnectionPoint
from _nsgroup import MonetaryQuantity # {urn:X-fsgim:fsgim}MonetaryQuantity
from _nsgroup import PiecewiseLinearSegment # {urn:X-fsgim:fsgim}PiecewiseLinearSegment
from _nsgroup import DPL # {urn:X-fsgim:fsgim}DPL
from _nsgroup import ExtendedInfoType # {urn:X-fsgim:fsgim}ExtendedInfoType
from _nsgroup import FSGIMIdentifiedObject # {urn:X-fsgim:fsgim}FSGIMIdentifiedObject
from _nsgroup import MasterFormatType # {urn:X-fsgim:fsgim}MasterFormatType
from _nsgroup import Name # {urn:X-fsgim:fsgim}Name
from _nsgroup import NameType # {urn:X-fsgim:fsgim}NameType
from _nsgroup import NameTypeAuthority # {urn:X-fsgim:fsgim}NameTypeAuthority
from _nsgroup import FSGIMSolar # {urn:X-fsgim:fsgim}FSGIMSolar
from _nsgroup import FSGIMWind # {urn:X-fsgim:fsgim}FSGIMWind
from _nsgroup import QualityMeasureType # {urn:X-fsgim:fsgim}QualityMeasureType
from _nsgroup import MovementDescription # {urn:X-fsgim:fsgim}MovementDescription
from _nsgroup import ApplicationSpecificExtensionBaseType # {urn:X-fsgim:fsgim}ApplicationSpecificExtensionBaseType
from _nsgroup import ArrayOfSignals # {urn:X-fsgim:fsgim}ArrayOfSignals
from _nsgroup import CurrentValueType # {urn:X-fsgim:fsgim}CurrentValueType
from _nsgroup import EiEventBaselineType # {urn:X-fsgim:fsgim}EiEventBaselineType
from _nsgroup import EiEventType # {urn:X-fsgim:fsgim}EiEventType
from _nsgroup import EiMarketContextType # {urn:X-fsgim:fsgim}EiMarketContextType
from _nsgroup import EventSignalTypeBase # {urn:X-fsgim:fsgim}EventSignalTypeBase
from _nsgroup import PayloadBaseType # {urn:X-fsgim:fsgim}PayloadBaseType
from _nsgroup import refID # {urn:X-fsgim:fsgim}refID
from _nsgroup import ReportSpecifierType # {urn:X-fsgim:fsgim}ReportSpecifierType
from _nsgroup import SimpleLevelContextType # {urn:X-fsgim:fsgim}SimpleLevelContextType
from _nsgroup import SpecifierPayloadType # {urn:X-fsgim:fsgim}SpecifierPayloadType
from _nsgroup import PowerCurve # {urn:X-fsgim:fsgim}PowerCurve
from _nsgroup import PowerRatings # {urn:X-fsgim:fsgim}PowerRatings
from _nsgroup import EnergyRouter # {urn:X-fsgim:fsgim}EnergyRouter
from _nsgroup import ArrayOfTerms # {urn:X-fsgim:fsgim}ArrayOfTerms
from _nsgroup import BaseTermType # {urn:X-fsgim:fsgim}BaseTermType
from _nsgroup import MarketContextNameType # {urn:X-fsgim:fsgim}MarketContextNameType
from _nsgroup import StandardTermsSetType # {urn:X-fsgim:fsgim}StandardTermsSetType
from _nsgroup import StandardTermsType # {urn:X-fsgim:fsgim}StandardTermsType
from _nsgroup import ItemBaseType # {urn:X-fsgim:fsgim}ItemBaseType
from _nsgroup import Measurement # {urn:X-fsgim:fsgim}Measurement
from _nsgroup import AggregationProperties # {urn:X-fsgim:fsgim}AggregationProperties
from _nsgroup import PercentageRange # {urn:X-fsgim:fsgim}PercentageRange
from _nsgroup import WeatherModifier # {urn:X-fsgim:fsgim}WeatherModifier
from _nsgroup import WxCode # {urn:X-fsgim:fsgim}WxCode
from _nsgroup import ReportProcess # {urn:X-fsgim:fsgim}ReportProcess
from _nsgroup import ArrayOfRampSegments # {urn:X-fsgim:fsgim}ArrayOfRampSegments
from _nsgroup import OfferSegmentType # {urn:X-fsgim:fsgim}OfferSegmentType
from _nsgroup import ResourceTypeType # {urn:X-fsgim:fsgim}ResourceTypeType
from _nsgroup import ObservationCollection # {urn:X-fsgim:fsgim}ObservationCollection
from _nsgroup import AbstractMeasure # {urn:X-fsgim:fsgim}AbstractMeasure
from _nsgroup import Bearing # {urn:X-fsgim:fsgim}Bearing
from _nsgroup import Percentage # {urn:X-fsgim:fsgim}Percentage
from _nsgroup import ExtentOf # {urn:X-fsgim:fsgim}ExtentOf
from _nsgroup import LPL # {urn:X-fsgim:fsgim}LPL
from _nsgroup import CUG # {urn:X-fsgim:fsgim}CUG
from _nsgroup import ENG # {urn:X-fsgim:fsgim}ENG
from _nsgroup import ING # {urn:X-fsgim:fsgim}ING
from _nsgroup import ORG # {urn:X-fsgim:fsgim}ORG
from _nsgroup import SPG # {urn:X-fsgim:fsgim}SPG
from _nsgroup import APC # {urn:X-fsgim:fsgim}APC
from _nsgroup import DPC # {urn:X-fsgim:fsgim}DPC
from _nsgroup import ENC # {urn:X-fsgim:fsgim}ENC
from _nsgroup import SPC # {urn:X-fsgim:fsgim}SPC
from _nsgroup import BCR # {urn:X-fsgim:fsgim}BCR
from _nsgroup import ENS # {urn:X-fsgim:fsgim}ENS
from _nsgroup import INS # {urn:X-fsgim:fsgim}INS
from _nsgroup import SPS # {urn:X-fsgim:fsgim}SPS
from _nsgroup import DEL # {urn:X-fsgim:fsgim}DEL
from _nsgroup import HarmonicMeasurandCDC # {urn:X-fsgim:fsgim}HarmonicMeasurandCDC
from _nsgroup import RangeDeadbandCDC # {urn:X-fsgim:fsgim}RangeDeadbandCDC
from _nsgroup import WYE # {urn:X-fsgim:fsgim}WYE
from _nsgroup import ASG # {urn:X-fsgim:fsgim}ASG
from _nsgroup import CSG # {urn:X-fsgim:fsgim}CSG
from _nsgroup import DomainLN # {urn:X-fsgim:fsgim}DomainLN
from _nsgroup import ChargeStatusENS # {urn:X-fsgim:fsgim}ChargeStatusENS
from _nsgroup import ConnectionTypeENS # {urn:X-fsgim:fsgim}ConnectionTypeENS
from _nsgroup import GeneratorOperationStatusENS # {urn:X-fsgim:fsgim}GeneratorOperationStatusENS
from _nsgroup import SCR # {urn:X-fsgim:fsgim}SCR
from _nsgroup import SequenceDirectionENS # {urn:X-fsgim:fsgim}SequenceDirectionENS
from _nsgroup import DQ_Element # {urn:X-fsgim:fsgim}DQ_Element
from _nsgroup import DirectPosition # {urn:X-fsgim:fsgim}DirectPosition
from _nsgroup import GM_Envelope # {urn:X-fsgim:fsgim}GM_Envelope
from _nsgroup import MD_Metadata # {urn:X-fsgim:fsgim}MD_Metadata
from _nsgroup import EnumDA # {urn:X-fsgim:fsgim}EnumDA
from _nsgroup import MD_Identifier # {urn:X-fsgim:fsgim}MD_Identifier
from _nsgroup import AnalogueValue # {urn:X-fsgim:fsgim}AnalogueValue
from _nsgroup import DetailQual # {urn:X-fsgim:fsgim}DetailQual
from _nsgroup import Originator # {urn:X-fsgim:fsgim}Originator
from _nsgroup import Point # {urn:X-fsgim:fsgim}Point
from _nsgroup import PulseConfig # {urn:X-fsgim:fsgim}PulseConfig
from _nsgroup import Quality # {urn:X-fsgim:fsgim}Quality
from _nsgroup import RangeConfig # {urn:X-fsgim:fsgim}RangeConfig
from _nsgroup import ScaledValueConfig # {urn:X-fsgim:fsgim}ScaledValueConfig
from _nsgroup import Unit # {urn:X-fsgim:fsgim}Unit
from _nsgroup import Vector # {urn:X-fsgim:fsgim}Vector
from _nsgroup import ObjectReference # {urn:X-fsgim:fsgim}ObjectReference
from _nsgroup import CI_Address # {urn:X-fsgim:fsgim}CI_Address
from _nsgroup import CI_Citation # {urn:X-fsgim:fsgim}CI_Citation
from _nsgroup import CI_Contact # {urn:X-fsgim:fsgim}CI_Contact
from _nsgroup import CI_OnlineResource # {urn:X-fsgim:fsgim}CI_OnlineResource
from _nsgroup import CI_ResponsibleParty # {urn:X-fsgim:fsgim}CI_ResponsibleParty
from _nsgroup import CI_Series # {urn:X-fsgim:fsgim}CI_Series
from _nsgroup import CI_Telephone # {urn:X-fsgim:fsgim}CI_Telephone
from _nsgroup import PT_Locale # {urn:X-fsgim:fsgim}PT_Locale
from _nsgroup import EMIntervalDataRestrictions # {urn:X-fsgim:fsgim}EMIntervalDataRestrictions
from _nsgroup import ServiceSupplierData # {urn:X-fsgim:fsgim}ServiceSupplierData
from _nsgroup import Aggregation # {urn:X-fsgim:fsgim}Aggregation
from _nsgroup import RuleSet # {urn:X-fsgim:fsgim}RuleSet
from _nsgroup import EmixInterfaceType # {urn:X-fsgim:fsgim}EmixInterfaceType
from _nsgroup import OptionTypeEnumeratedType # {urn:X-fsgim:fsgim}OptionTypeEnumeratedType
from _nsgroup import PriceMultiplierType # {urn:X-fsgim:fsgim}PriceMultiplierType
from _nsgroup import PriceRelativeType # {urn:X-fsgim:fsgim}PriceRelativeType
from _nsgroup import PriceType # {urn:X-fsgim:fsgim}PriceType
from _nsgroup import Customer # {urn:X-fsgim:fsgim}Customer
from _nsgroup import CustomerAuthorisation # {urn:X-fsgim:fsgim}CustomerAuthorisation
from _nsgroup import ElectricPowerQualitySummary # {urn:X-fsgim:fsgim}ElectricPowerQualitySummary
from _nsgroup import IntervalBlock # {urn:X-fsgim:fsgim}IntervalBlock
from _nsgroup import IntervalReading # {urn:X-fsgim:fsgim}IntervalReading
from _nsgroup import MeterReading # {urn:X-fsgim:fsgim}MeterReading
from _nsgroup import Reading # {urn:X-fsgim:fsgim}Reading
from _nsgroup import UsagePoint # {urn:X-fsgim:fsgim}UsagePoint
from _nsgroup import UsageSummary # {urn:X-fsgim:fsgim}UsageSummary
from _nsgroup import LocalDateTimeInterval # {urn:X-fsgim:fsgim}LocalDateTimeInterval
from _nsgroup import LocalTimeParameters # {urn:X-fsgim:fsgim}LocalTimeParameters
from _nsgroup import UTCDateTimeInterval # {urn:X-fsgim:fsgim}UTCDateTimeInterval
from _nsgroup import IntervalType # {urn:X-fsgim:fsgim}IntervalType
from _nsgroup import Randomization # {urn:X-fsgim:fsgim}Randomization
from _nsgroup import RelationLink # {urn:X-fsgim:fsgim}RelationLink
from _nsgroup import FSGIMPayloadBaseType # {urn:X-fsgim:fsgim}FSGIMPayloadBaseType
from _nsgroup import Circuit # {urn:X-fsgim:fsgim}Circuit
from _nsgroup import ComponentElement # {urn:X-fsgim:fsgim}ComponentElement
from _nsgroup import Device # {urn:X-fsgim:fsgim}Device
from _nsgroup import Irradiance # {urn:X-fsgim:fsgim}Irradiance
from _nsgroup import RelativeHumidity # {urn:X-fsgim:fsgim}RelativeHumidity
from _nsgroup import PowerQualityWarrantType # {urn:X-fsgim:fsgim}PowerQualityWarrantType
from _nsgroup import ApplicationSpecificContextBaseType # {urn:X-fsgim:fsgim}ApplicationSpecificContextBaseType
from _nsgroup import ApplicationSpecificPayloadBaseType # {urn:X-fsgim:fsgim}ApplicationSpecificPayloadBaseType
from _nsgroup import EiEventSignalType # {urn:X-fsgim:fsgim}EiEventSignalType
from _nsgroup import EiTargetType # {urn:X-fsgim:fsgim}EiTargetType
from _nsgroup import EventDescriptorType # {urn:X-fsgim:fsgim}EventDescriptorType
from _nsgroup import FSGIMEventSignalType # {urn:X-fsgim:fsgim}FSGIMEventSignalType
from _nsgroup import PayloadApplicationSpecificType # {urn:X-fsgim:fsgim}PayloadApplicationSpecificType
from _nsgroup import PayloadEmixType # {urn:X-fsgim:fsgim}PayloadEmixType
from _nsgroup import PayloadFloatType # {urn:X-fsgim:fsgim}PayloadFloatType
from _nsgroup import PayloadLevelType # {urn:X-fsgim:fsgim}PayloadLevelType
from _nsgroup import PayloadPriceMultiplierType # {urn:X-fsgim:fsgim}PayloadPriceMultiplierType
from _nsgroup import PayloadPriceRelativeType # {urn:X-fsgim:fsgim}PayloadPriceRelativeType
from _nsgroup import PayloadPriceType # {urn:X-fsgim:fsgim}PayloadPriceType
from _nsgroup import PayloadProductType # {urn:X-fsgim:fsgim}PayloadProductType
from _nsgroup import PayloadQuantityType # {urn:X-fsgim:fsgim}PayloadQuantityType
from _nsgroup import DERMeasurement # {urn:X-fsgim:fsgim}DERMeasurement
from _nsgroup import DERComplexOutputRamping # {urn:X-fsgim:fsgim}DERComplexOutputRamping
from _nsgroup import DERCostParameters # {urn:X-fsgim:fsgim}DERCostParameters
from _nsgroup import DERDeviceControllerCharacteristics # {urn:X-fsgim:fsgim}DERDeviceControllerCharacteristics
from _nsgroup import DERGeneratorRatings # {urn:X-fsgim:fsgim}DERGeneratorRatings
from _nsgroup import DEROperationalModeControls # {urn:X-fsgim:fsgim}DEROperationalModeControls
from _nsgroup import DERThermalStorage # {urn:X-fsgim:fsgim}DERThermalStorage
from _nsgroup import DERUnitControlActions # {urn:X-fsgim:fsgim}DERUnitControlActions
from _nsgroup import DERUnitGenerator # {urn:X-fsgim:fsgim}DERUnitGenerator
from _nsgroup import DERUnitStatus # {urn:X-fsgim:fsgim}DERUnitStatus
from _nsgroup import BidirectionalCombiner # {urn:X-fsgim:fsgim}BidirectionalCombiner
from _nsgroup import GridTransferSwitch # {urn:X-fsgim:fsgim}GridTransferSwitch
from _nsgroup import RouterConnectionPoint # {urn:X-fsgim:fsgim}RouterConnectionPoint
from _nsgroup import TransferSwitch # {urn:X-fsgim:fsgim}TransferSwitch
from _nsgroup import UnidirectionalCombiner # {urn:X-fsgim:fsgim}UnidirectionalCombiner
from _nsgroup import AvailabilityScheduleType # {urn:X-fsgim:fsgim}AvailabilityScheduleType
from _nsgroup import MarketGranularityType # {urn:X-fsgim:fsgim}MarketGranularityType
from _nsgroup import MaximumConsecutiveDurationsType # {urn:X-fsgim:fsgim}MaximumConsecutiveDurationsType
from _nsgroup import MaximumInvocationsPerDurationType # {urn:X-fsgim:fsgim}MaximumInvocationsPerDurationType
from _nsgroup import MaximumNotificationDurationType # {urn:X-fsgim:fsgim}MaximumNotificationDurationType
from _nsgroup import MaximumResponseDurationType # {urn:X-fsgim:fsgim}MaximumResponseDurationType
from _nsgroup import MaximumRunDurationType # {urn:X-fsgim:fsgim}MaximumRunDurationType
from _nsgroup import MinimumDurationBetweenInvocationsType # {urn:X-fsgim:fsgim}MinimumDurationBetweenInvocationsType
from _nsgroup import MinimumEconomicRequirementType # {urn:X-fsgim:fsgim}MinimumEconomicRequirementType
from _nsgroup import MinimumNotificationDurationType # {urn:X-fsgim:fsgim}MinimumNotificationDurationType
from _nsgroup import MinimumRecoveryDurationType # {urn:X-fsgim:fsgim}MinimumRecoveryDurationType
from _nsgroup import MinimumRemunerationRateType # {urn:X-fsgim:fsgim}MinimumRemunerationRateType
from _nsgroup import MinimumResponseDurationType # {urn:X-fsgim:fsgim}MinimumResponseDurationType
from _nsgroup import MinimumRunDurationType # {urn:X-fsgim:fsgim}MinimumRunDurationType
from _nsgroup import MinimumStartsPerDurationType # {urn:X-fsgim:fsgim}MinimumStartsPerDurationType
from _nsgroup import NotificationScheduleType # {urn:X-fsgim:fsgim}NotificationScheduleType
from _nsgroup import RequiredStartupRemunerationType # {urn:X-fsgim:fsgim}RequiredStartupRemunerationType
from _nsgroup import ResponseTimeType # {urn:X-fsgim:fsgim}ResponseTimeType
from _nsgroup import UnavailabilityScheduleType # {urn:X-fsgim:fsgim}UnavailabilityScheduleType
from _nsgroup import MeasurementMetadataType # {urn:X-fsgim:fsgim}MeasurementMetadataType
from _nsgroup import MeasurementQuantityRestrictions # {urn:X-fsgim:fsgim}MeasurementQuantityRestrictions
from _nsgroup import MeasurementSet # {urn:X-fsgim:fsgim}MeasurementSet
from _nsgroup import WindDirection # {urn:X-fsgim:fsgim}WindDirection
from _nsgroup import AbstractFeature # {urn:X-fsgim:fsgim}AbstractFeature
from _nsgroup import OfferCurveType # {urn:X-fsgim:fsgim}OfferCurveType
from _nsgroup import PowerResponseType # {urn:X-fsgim:fsgim}PowerResponseType
from _nsgroup import Observation # {urn:X-fsgim:fsgim}Observation
from _nsgroup import Angle # {urn:X-fsgim:fsgim}Angle
from _nsgroup import Distance # {urn:X-fsgim:fsgim}Distance
from _nsgroup import Luminance # {urn:X-fsgim:fsgim}Luminance
from _nsgroup import Pressure # {urn:X-fsgim:fsgim}Pressure
from _nsgroup import Speed # {urn:X-fsgim:fsgim}Speed
from _nsgroup import Temperature # {urn:X-fsgim:fsgim}Temperature
from _nsgroup import ENCBehaviourMode # {urn:X-fsgim:fsgim}ENCBehaviourMode
from _nsgroup import ENGCalcIntervalType # {urn:X-fsgim:fsgim}ENGCalcIntervalType
from _nsgroup import ENGCalcMethod # {urn:X-fsgim:fsgim}ENGCalcMethod
from _nsgroup import ENGCalcMode # {urn:X-fsgim:fsgim}ENGCalcMode
from _nsgroup import ENGPfSign # {urn:X-fsgim:fsgim}ENGPfSign
from _nsgroup import ENGSTotalCalcMethod # {urn:X-fsgim:fsgim}ENGSTotalCalcMethod
from _nsgroup import ENSAdjustment # {urn:X-fsgim:fsgim}ENSAdjustment
from _nsgroup import ENSBehaviourMode # {urn:X-fsgim:fsgim}ENSBehaviourMode
from _nsgroup import ENSHealth # {urn:X-fsgim:fsgim}ENSHealth
from _nsgroup import SPCTransient # {urn:X-fsgim:fsgim}SPCTransient
from _nsgroup import SPSTransient # {urn:X-fsgim:fsgim}SPSTransient
from _nsgroup import CMV # {urn:X-fsgim:fsgim}CMV
from _nsgroup import HMV # {urn:X-fsgim:fsgim}HMV
from _nsgroup import MV # {urn:X-fsgim:fsgim}MV
from _nsgroup import LLN0 # {urn:X-fsgim:fsgim}LLN0
from _nsgroup import LPHD # {urn:X-fsgim:fsgim}LPHD
from _nsgroup import EM # {urn:X-fsgim:fsgim}EM
from _nsgroup import EMGenerationType # {urn:X-fsgim:fsgim}EMGenerationType
from _nsgroup import EMIntervalData # {urn:X-fsgim:fsgim}EMIntervalData
from _nsgroup import EMPowerResponseType # {urn:X-fsgim:fsgim}EMPowerResponseType
from _nsgroup import EMUsagePoint # {urn:X-fsgim:fsgim}EMUsagePoint
from _nsgroup import IntervalDataContainerRestrictions # {urn:X-fsgim:fsgim}IntervalDataContainerRestrictions
from _nsgroup import Collection # {urn:X-fsgim:fsgim}Collection
from _nsgroup import ServiceAreaType # {urn:X-fsgim:fsgim}ServiceAreaType
from _nsgroup import Meter # {urn:X-fsgim:fsgim}Meter
from _nsgroup import AggregatedPnodeType # {urn:X-fsgim:fsgim}AggregatedPnodeType
from _nsgroup import EndDeviceAssetType # {urn:X-fsgim:fsgim}EndDeviceAssetType
from _nsgroup import MeterAssetType # {urn:X-fsgim:fsgim}MeterAssetType
from _nsgroup import PnodeType # {urn:X-fsgim:fsgim}PnodeType
from _nsgroup import ServiceDeliveryPointType # {urn:X-fsgim:fsgim}ServiceDeliveryPointType
from _nsgroup import ServiceLocationType # {urn:X-fsgim:fsgim}ServiceLocationType
from _nsgroup import TransportInterfaceType # {urn:X-fsgim:fsgim}TransportInterfaceType
from _nsgroup import Generator # {urn:X-fsgim:fsgim}Generator
from _nsgroup import GluonTypeRestrictions # {urn:X-fsgim:fsgim}GluonTypeRestrictions
from _nsgroup import FSGIMPayloadFloatType # {urn:X-fsgim:fsgim}FSGIMPayloadFloatType
from _nsgroup import FSGIMPayloadLevelType # {urn:X-fsgim:fsgim}FSGIMPayloadLevelType
from _nsgroup import FSGIMPayloadQuantityType # {urn:X-fsgim:fsgim}FSGIMPayloadQuantityType
from _nsgroup import Load # {urn:X-fsgim:fsgim}Load
from _nsgroup import GridCircuit # {urn:X-fsgim:fsgim}GridCircuit
from _nsgroup import FSGIMWeatherArea # {urn:X-fsgim:fsgim}FSGIMWeatherArea
from _nsgroup import FSGIMWeatherBase # {urn:X-fsgim:fsgim}FSGIMWeatherBase
from _nsgroup import FSGIMWeatherForecast # {urn:X-fsgim:fsgim}FSGIMWeatherForecast
from _nsgroup import FSGIMWeatherObservation # {urn:X-fsgim:fsgim}FSGIMWeatherObservation
from _nsgroup import FSGIMWeatherReport # {urn:X-fsgim:fsgim}FSGIMWeatherReport
from _nsgroup import FSGIMWeatherTrend # {urn:X-fsgim:fsgim}FSGIMWeatherTrend
from _nsgroup import AdjustedFullDRDemandAggregationRestrictions # {urn:X-fsgim:fsgim}AdjustedFullDRDemandAggregationRestrictions
from _nsgroup import AdjustedFullDRSupplyAggregationRestrictions # {urn:X-fsgim:fsgim}AdjustedFullDRSupplyAggregationRestrictions
from _nsgroup import AdjustedNoDRDemandAggregationRestrictions # {urn:X-fsgim:fsgim}AdjustedNoDRDemandAggregationRestrictions
from _nsgroup import AdjustedNoDRSupplyAggregationRestrictions # {urn:X-fsgim:fsgim}AdjustedNoDRSupplyAggregationRestrictions
from _nsgroup import DemandAggregationRestrictions # {urn:X-fsgim:fsgim}DemandAggregationRestrictions
from _nsgroup import ElectricalEnergyStoredAggregationRestrictions # {urn:X-fsgim:fsgim}ElectricalEnergyStoredAggregationRestrictions
from _nsgroup import EmissionsGeneratedAggregationRestrictions # {urn:X-fsgim:fsgim}EmissionsGeneratedAggregationRestrictions
from _nsgroup import EmissionsGenerationRateAggregationRestrictions # {urn:X-fsgim:fsgim}EmissionsGenerationRateAggregationRestrictions
from _nsgroup import EnergyConsumedAggregationRestrictions # {urn:X-fsgim:fsgim}EnergyConsumedAggregationRestrictions
from _nsgroup import EnergySuppliedAggregationRestrictions # {urn:X-fsgim:fsgim}EnergySuppliedAggregationRestrictions
from _nsgroup import NetDemandAggregationRestrictions # {urn:X-fsgim:fsgim}NetDemandAggregationRestrictions
from _nsgroup import NetEnergyConsumedAggregationRestrictions # {urn:X-fsgim:fsgim}NetEnergyConsumedAggregationRestrictions
from _nsgroup import SupplyAggregationRestrictions # {urn:X-fsgim:fsgim}SupplyAggregationRestrictions
from _nsgroup import ThermalEnergyStoredAggregationRestrictions # {urn:X-fsgim:fsgim}ThermalEnergyStoredAggregationRestrictions
from _nsgroup import AbstractPhenomenon # {urn:X-fsgim:fsgim}AbstractPhenomenon
from _nsgroup import WxCondition # {urn:X-fsgim:fsgim}WxCondition
from _nsgroup import PowerItemType # {urn:X-fsgim:fsgim}PowerItemType
from _nsgroup import PowerMeasurementsSetRestrictions # {urn:X-fsgim:fsgim}PowerMeasurementsSetRestrictions
from _nsgroup import EnergyItemType # {urn:X-fsgim:fsgim}EnergyItemType
from _nsgroup import EnergyMeasurementsSetRestrictions # {urn:X-fsgim:fsgim}EnergyMeasurementsSetRestrictions
from _nsgroup import ThermalEnergyMeasurementsSetRestrictions # {urn:X-fsgim:fsgim}ThermalEnergyMeasurementsSetRestrictions
from _nsgroup import EmissionsItemType # {urn:X-fsgim:fsgim}EmissionsItemType
from _nsgroup import EmissionsMeasurementsSetRestrictions # {urn:X-fsgim:fsgim}EmissionsMeasurementsSetRestrictions
from _nsgroup import MeasurementQuantity # {urn:X-fsgim:fsgim}MeasurementQuantity
from _nsgroup import AirTemperature # {urn:X-fsgim:fsgim}AirTemperature
from _nsgroup import HorizontalDistance # {urn:X-fsgim:fsgim}HorizontalDistance
from _nsgroup import VerticalDistance # {urn:X-fsgim:fsgim}VerticalDistance
from _nsgroup import WindGust # {urn:X-fsgim:fsgim}WindGust
from _nsgroup import WindSpeed # {urn:X-fsgim:fsgim}WindSpeed
from _nsgroup import LoadReductionType # {urn:X-fsgim:fsgim}LoadReductionType
from _nsgroup import EMLoadReductionType # {urn:X-fsgim:fsgim}EMLoadReductionType
from _nsgroup import IntervalDataContainer # {urn:X-fsgim:fsgim}IntervalDataContainer
from _nsgroup import AllResourcesInEMDomain # {urn:X-fsgim:fsgim}AllResourcesInEMDomain
from _nsgroup import FilteredCollection # {urn:X-fsgim:fsgim}FilteredCollection
from _nsgroup import ElectricMeter # {urn:X-fsgim:fsgim}ElectricMeter
from _nsgroup import EmissionsMeter # {urn:X-fsgim:fsgim}EmissionsMeter
from _nsgroup import DispatchableGenerator # {urn:X-fsgim:fsgim}DispatchableGenerator
from _nsgroup import GluonType # {urn:X-fsgim:fsgim}GluonType
from _nsgroup import CurtailableLoad # {urn:X-fsgim:fsgim}CurtailableLoad
from _nsgroup import FSGIMPrecipitation # {urn:X-fsgim:fsgim}FSGIMPrecipitation
from _nsgroup import AdjustedFullDRDemandAggregation # {urn:X-fsgim:fsgim}AdjustedFullDRDemandAggregation
from _nsgroup import AdjustedFullDRSupplyAggregation # {urn:X-fsgim:fsgim}AdjustedFullDRSupplyAggregation
from _nsgroup import AdjustedNoDRDemandAggregation # {urn:X-fsgim:fsgim}AdjustedNoDRDemandAggregation
from _nsgroup import AdjustedNoDRSupplyAggregation # {urn:X-fsgim:fsgim}AdjustedNoDRSupplyAggregation
from _nsgroup import DemandAggregation # {urn:X-fsgim:fsgim}DemandAggregation
from _nsgroup import ElectricalEnergyStoredAggregation # {urn:X-fsgim:fsgim}ElectricalEnergyStoredAggregation
from _nsgroup import EmissionsGeneratedAggregation # {urn:X-fsgim:fsgim}EmissionsGeneratedAggregation
from _nsgroup import EmissionsGenerationRateAggregation # {urn:X-fsgim:fsgim}EmissionsGenerationRateAggregation
from _nsgroup import EnergyConsumedAggregation # {urn:X-fsgim:fsgim}EnergyConsumedAggregation
from _nsgroup import EnergySuppliedAggregation # {urn:X-fsgim:fsgim}EnergySuppliedAggregation
from _nsgroup import NetDemandAggregation # {urn:X-fsgim:fsgim}NetDemandAggregation
from _nsgroup import NetEnergyConsumedAggregation # {urn:X-fsgim:fsgim}NetEnergyConsumedAggregation
from _nsgroup import SupplyAggregation # {urn:X-fsgim:fsgim}SupplyAggregation
from _nsgroup import ThermalEnergyStoredAggregation # {urn:X-fsgim:fsgim}ThermalEnergyStoredAggregation
from _nsgroup import PowerApparentType # {urn:X-fsgim:fsgim}PowerApparentType
from _nsgroup import PowerMeasurementsSet # {urn:X-fsgim:fsgim}PowerMeasurementsSet
from _nsgroup import PowerQuantityType # {urn:X-fsgim:fsgim}PowerQuantityType
from _nsgroup import PowerReactiveType # {urn:X-fsgim:fsgim}PowerReactiveType
from _nsgroup import PowerRealType # {urn:X-fsgim:fsgim}PowerRealType
from _nsgroup import PowerThermalType # {urn:X-fsgim:fsgim}PowerThermalType
from _nsgroup import CloudCondition # {urn:X-fsgim:fsgim}CloudCondition
from _nsgroup import EnergyApparentType # {urn:X-fsgim:fsgim}EnergyApparentType
from _nsgroup import EnergyMeasurementsSet # {urn:X-fsgim:fsgim}EnergyMeasurementsSet
from _nsgroup import EnergyQuantityType # {urn:X-fsgim:fsgim}EnergyQuantityType
from _nsgroup import EnergyReactiveType # {urn:X-fsgim:fsgim}EnergyReactiveType
from _nsgroup import EnergyRealType # {urn:X-fsgim:fsgim}EnergyRealType
from _nsgroup import EnergyThermalType # {urn:X-fsgim:fsgim}EnergyThermalType
from _nsgroup import ThermalEnergyMeasurementsSet # {urn:X-fsgim:fsgim}ThermalEnergyMeasurementsSet
from _nsgroup import EmissionsConcentrationType # {urn:X-fsgim:fsgim}EmissionsConcentrationType
from _nsgroup import EmissionsMassRateType # {urn:X-fsgim:fsgim}EmissionsMassRateType
from _nsgroup import EmissionsMassType # {urn:X-fsgim:fsgim}EmissionsMassType
from _nsgroup import EmissionsMeasurementsSet # {urn:X-fsgim:fsgim}EmissionsMeasurementsSet
from _nsgroup import EmissionsQuantityType # {urn:X-fsgim:fsgim}EmissionsQuantityType
from _nsgroup import EmissionsRateMeasurementsSet # {urn:X-fsgim:fsgim}EmissionsRateMeasurementsSet
from _nsgroup import CloudHeight # {urn:X-fsgim:fsgim}CloudHeight
from _nsgroup import Depth # {urn:X-fsgim:fsgim}Depth
from _nsgroup import HorizontalVisibilityDistance # {urn:X-fsgim:fsgim}HorizontalVisibilityDistance
from _nsgroup import VerticalVisibilityDistance # {urn:X-fsgim:fsgim}VerticalVisibilityDistance
from _nsgroup import Sequence # {urn:X-fsgim:fsgim}Sequence
from _nsgroup import EmixBaseType # {urn:X-fsgim:fsgim}EmixBaseType
from _nsgroup import PowerApparentQuantityRestrictions # {urn:X-fsgim:fsgim}PowerApparentQuantityRestrictions
from _nsgroup import PowerReactiveQuantityRestrictions # {urn:X-fsgim:fsgim}PowerReactiveQuantityRestrictions
from _nsgroup import PowerRealQuantityRestrictions # {urn:X-fsgim:fsgim}PowerRealQuantityRestrictions
from _nsgroup import PowerThermalQuantityRestrictions # {urn:X-fsgim:fsgim}PowerThermalQuantityRestrictions
from _nsgroup import EnergyApparentQuantityRestrictions # {urn:X-fsgim:fsgim}EnergyApparentQuantityRestrictions
from _nsgroup import EnergyReactiveQuantityRestrictions # {urn:X-fsgim:fsgim}EnergyReactiveQuantityRestrictions
from _nsgroup import StoreableEnergyQuantity # {urn:X-fsgim:fsgim}StoreableEnergyQuantity
from _nsgroup import EmissionsConcentrationQuantityRestrictions # {urn:X-fsgim:fsgim}EmissionsConcentrationQuantityRestrictions
from _nsgroup import EmissionsMassQuantityRestrictions # {urn:X-fsgim:fsgim}EmissionsMassQuantityRestrictions
from _nsgroup import EmissionsMassRateQuantityRestrictions # {urn:X-fsgim:fsgim}EmissionsMassRateQuantityRestrictions
from _nsgroup import ForecastSequence # {urn:X-fsgim:fsgim}ForecastSequence
from _nsgroup import DeliveryType # {urn:X-fsgim:fsgim}DeliveryType
from _nsgroup import EmixOptionType # {urn:X-fsgim:fsgim}EmixOptionType
from _nsgroup import ProductType # {urn:X-fsgim:fsgim}ProductType
from _nsgroup import PowerApparentQuantity # {urn:X-fsgim:fsgim}PowerApparentQuantity
from _nsgroup import PowerReactiveQuantity # {urn:X-fsgim:fsgim}PowerReactiveQuantity
from _nsgroup import PowerRealQuantity # {urn:X-fsgim:fsgim}PowerRealQuantity
from _nsgroup import PowerThermalQuantity # {urn:X-fsgim:fsgim}PowerThermalQuantity
from _nsgroup import EnergyApparentQuantity # {urn:X-fsgim:fsgim}EnergyApparentQuantity
from _nsgroup import EnergyReactiveQuantity # {urn:X-fsgim:fsgim}EnergyReactiveQuantity
from _nsgroup import EnergyRealQuantityRestrictions # {urn:X-fsgim:fsgim}EnergyRealQuantityRestrictions
from _nsgroup import EnergyThermalQuantityRestrictions # {urn:X-fsgim:fsgim}EnergyThermalQuantityRestrictions
from _nsgroup import EmissionsConcentrationQuantity # {urn:X-fsgim:fsgim}EmissionsConcentrationQuantity
from _nsgroup import EmissionsMassQuantity # {urn:X-fsgim:fsgim}EmissionsMassQuantity
from _nsgroup import EmissionsMassRateQuantity # {urn:X-fsgim:fsgim}EmissionsMassRateQuantity
from _nsgroup import EnergyRealQuantity # {urn:X-fsgim:fsgim}EnergyRealQuantity
from _nsgroup import EnergyThermalQuantity # {urn:X-fsgim:fsgim}EnergyThermalQuantity
from _nsgroup import DemandTarget_ # {urn:X-fsgim:fsgim}DemandTarget
from _nsgroup import EMPresentData_ # {urn:X-fsgim:fsgim}EMPresentData
from _nsgroup import PeakPowerData_ # {urn:X-fsgim:fsgim}PeakPowerData
from _nsgroup import EnvelopeContentsType_ # {urn:X-fsgim:fsgim}EnvelopeContentsType
from _nsgroup import OptionTypeType_ # {urn:X-fsgim:fsgim}OptionTypeType
from _nsgroup import PriceBaseType_ # {urn:X-fsgim:fsgim}PriceBaseType
from _nsgroup import SideType # {urn:X-fsgim:fsgim}SideType
from _nsgroup import TransactiveStateType # {urn:X-fsgim:fsgim}TransactiveStateType
from _nsgroup import AccumulationKind # {urn:X-fsgim:fsgim}AccumulationKind
from _nsgroup import BaseCIM_CombinedVersion_ # {urn:X-fsgim:fsgim}BaseCIM_CombinedVersion
from _nsgroup import CommodityKind # {urn:X-fsgim:fsgim}CommodityKind
from _nsgroup import CustomerAgreement_ # {urn:X-fsgim:fsgim}CustomerAgreement
from _nsgroup import DataQualifierKind # {urn:X-fsgim:fsgim}DataQualifierKind
from _nsgroup import EndDeviceAsset_ # {urn:X-fsgim:fsgim}EndDeviceAsset
from _nsgroup import EnergyUsageInformation_ # {urn:X-fsgim:fsgim}EnergyUsageInformation
from _nsgroup import FlowDirectionKind # {urn:X-fsgim:fsgim}FlowDirectionKind
from _nsgroup import LineItem_ # {urn:X-fsgim:fsgim}LineItem
from _nsgroup import MacroPeriodKind # {urn:X-fsgim:fsgim}MacroPeriodKind
from _nsgroup import MeasurementKind # {urn:X-fsgim:fsgim}MeasurementKind
from _nsgroup import MeasuringPeriodKind # {urn:X-fsgim:fsgim}MeasuringPeriodKind
from _nsgroup import NAESB_EUI_Version_ # {urn:X-fsgim:fsgim}NAESB_EUI_Version
from _nsgroup import PhaseCodeKind # {urn:X-fsgim:fsgim}PhaseCodeKind
from _nsgroup import PositionPoint_ # {urn:X-fsgim:fsgim}PositionPoint
from _nsgroup import RationalNumber_ # {urn:X-fsgim:fsgim}RationalNumber
from _nsgroup import ReadingInterharmonic_ # {urn:X-fsgim:fsgim}ReadingInterharmonic
from _nsgroup import ReadingQuality_ # {urn:X-fsgim:fsgim}ReadingQuality
from _nsgroup import ReadingType_ # {urn:X-fsgim:fsgim}ReadingType
from _nsgroup import RoleFlags_ # {urn:X-fsgim:fsgim}RoleFlags
from _nsgroup import ServiceCategory_ # {urn:X-fsgim:fsgim}ServiceCategory
from _nsgroup import ServiceDeliveryPoint_ # {urn:X-fsgim:fsgim}ServiceDeliveryPoint
from _nsgroup import ServiceKind # {urn:X-fsgim:fsgim}ServiceKind
from _nsgroup import ServiceSupplier_ # {urn:X-fsgim:fsgim}ServiceSupplier
from _nsgroup import SummaryMeasurement_ # {urn:X-fsgim:fsgim}SummaryMeasurement
from _nsgroup import SupplierKind # {urn:X-fsgim:fsgim}SupplierKind
from _nsgroup import TariffProfile_ # {urn:X-fsgim:fsgim}TariffProfile
from _nsgroup import TimeAttributeKind # {urn:X-fsgim:fsgim}TimeAttributeKind
from _nsgroup import UnitEnergyPriceType_ # {urn:X-fsgim:fsgim}UnitEnergyPriceType
from _nsgroup import FSGIMAtomLink_ # {urn:X-fsgim:fsgim}FSGIMAtomLink
from _nsgroup import FSGIMWeatherAtomLink_ # {urn:X-fsgim:fsgim}FSGIMWeatherAtomLink
from _nsgroup import DERDatasheetEmissions_ # {urn:X-fsgim:fsgim}DERDatasheetEmissions
from _nsgroup import StorageType # {urn:X-fsgim:fsgim}StorageType
from _nsgroup import SupplyArrayElement_ # {urn:X-fsgim:fsgim}SupplyArrayElement
from _nsgroup import SupplyStatusType # {urn:X-fsgim:fsgim}SupplyStatusType
from _nsgroup import DateTimeInterval_ # {urn:X-fsgim:fsgim}DateTimeInterval
from _nsgroup import DstRule # {urn:X-fsgim:fsgim}DstRule
from _nsgroup import DstTransitionRule_ # {urn:X-fsgim:fsgim}DstTransitionRule
from _nsgroup import LocalDateTime # {urn:X-fsgim:fsgim}LocalDateTime
from _nsgroup import UTCDateTime # {urn:X-fsgim:fsgim}UTCDateTime
from _nsgroup import AttachType_ # {urn:X-fsgim:fsgim}AttachType
from _nsgroup import CTD_ANON # None
from _nsgroup import AvailabilityType_ # {urn:X-fsgim:fsgim}AvailabilityType
from _nsgroup import FreqRecurType # {urn:X-fsgim:fsgim}FreqRecurType
from _nsgroup import RelationshipType # {urn:X-fsgim:fsgim}RelationshipType
from _nsgroup import TemporalRelationshipType # {urn:X-fsgim:fsgim}TemporalRelationshipType
from _nsgroup import ToleranceValueType_ # {urn:X-fsgim:fsgim}ToleranceValueType
from _nsgroup import VavailabilityType_ # {urn:X-fsgim:fsgim}VavailabilityType
from _nsgroup import WeekdaySpecType_ # {urn:X-fsgim:fsgim}WeekdaySpecType
from _nsgroup import RecurType_ # {urn:X-fsgim:fsgim}RecurType
from _nsgroup import CurtailmentArrayElement_ # {urn:X-fsgim:fsgim}CurtailmentArrayElement
from _nsgroup import CurtailmentStatusType # {urn:X-fsgim:fsgim}CurtailmentStatusType
from _nsgroup import CurtailmentValueType_ # {urn:X-fsgim:fsgim}CurtailmentValueType
from _nsgroup import LoadStatusType # {urn:X-fsgim:fsgim}LoadStatusType
from _nsgroup import PowerRampSegmentType_2 as PowerRampSegmentType_ # {urn:X-fsgim:fsgim}PowerRampSegmentType
from _nsgroup import ConnectionPoint_ # {urn:X-fsgim:fsgim}ConnectionPoint
from _nsgroup import MonetaryQuantity_ # {urn:X-fsgim:fsgim}MonetaryQuantity
from _nsgroup import PiecewiseLinearSegment_ # {urn:X-fsgim:fsgim}PiecewiseLinearSegment
from _nsgroup import DeviceStatus # {urn:X-fsgim:fsgim}DeviceStatus
from _nsgroup import DPL_ # {urn:X-fsgim:fsgim}DPL
from _nsgroup import EFacilitySystem # {urn:X-fsgim:fsgim}EFacilitySystem
from _nsgroup import ExtendedInfoType_ # {urn:X-fsgim:fsgim}ExtendedInfoType
from _nsgroup import FSGIMIdentifiedObject_ # {urn:X-fsgim:fsgim}FSGIMIdentifiedObject
from _nsgroup import MasterFormatType_ # {urn:X-fsgim:fsgim}MasterFormatType
from _nsgroup import Name_ # {urn:X-fsgim:fsgim}Name
from _nsgroup import NameType_ # {urn:X-fsgim:fsgim}NameType
from _nsgroup import NameTypeAuthority_ # {urn:X-fsgim:fsgim}NameTypeAuthority
from _nsgroup import FSGIMSolar_ # {urn:X-fsgim:fsgim}FSGIMSolar
from _nsgroup import FSGIMWind_ # {urn:X-fsgim:fsgim}FSGIMWind
from _nsgroup import MeasurementProtocolEnumeratedType # {urn:X-fsgim:fsgim}MeasurementProtocolEnumeratedType
from _nsgroup import QualityMeasureType_ # {urn:X-fsgim:fsgim}QualityMeasureType
from _nsgroup import QualityTypeEnumeratedType # {urn:X-fsgim:fsgim}QualityTypeEnumeratedType
from _nsgroup import MovementDescription_ # {urn:X-fsgim:fsgim}MovementDescription
from _nsgroup import ObscurationTypes # {urn:X-fsgim:fsgim}ObscurationTypes
from _nsgroup import OtherPhenomenonTypes # {urn:X-fsgim:fsgim}OtherPhenomenonTypes
from _nsgroup import PrecipitationTypes # {urn:X-fsgim:fsgim}PrecipitationTypes
from _nsgroup import ApplicationSpecificExtensionBaseType_ # {urn:X-fsgim:fsgim}ApplicationSpecificExtensionBaseType
from _nsgroup import ArrayOfSignals_ # {urn:X-fsgim:fsgim}ArrayOfSignals
from _nsgroup import CurrentValueType_ # {urn:X-fsgim:fsgim}CurrentValueType
from _nsgroup import EiEventBaselineType_ # {urn:X-fsgim:fsgim}EiEventBaselineType
from _nsgroup import EiEventType_ # {urn:X-fsgim:fsgim}EiEventType
from _nsgroup import EiExtensionTokenType # {urn:X-fsgim:fsgim}EiExtensionTokenType
from _nsgroup import EiMarketContextType_ # {urn:X-fsgim:fsgim}EiMarketContextType
from _nsgroup import EventSignalTypeBase_ # {urn:X-fsgim:fsgim}EventSignalTypeBase
from _nsgroup import EventStatusEnumeratedType # {urn:X-fsgim:fsgim}EventStatusEnumeratedType
from _nsgroup import PayloadBaseType_ # {urn:X-fsgim:fsgim}PayloadBaseType
from _nsgroup import ReadingTypeEnumeratedType # {urn:X-fsgim:fsgim}ReadingTypeEnumeratedType
from _nsgroup import refID_ # {urn:X-fsgim:fsgim}refID
from _nsgroup import ReportSpecifierType_ # {urn:X-fsgim:fsgim}ReportSpecifierType
from _nsgroup import SignalTypeEnumeratedType # {urn:X-fsgim:fsgim}SignalTypeEnumeratedType
from _nsgroup import SimpleLevelContextType_ # {urn:X-fsgim:fsgim}SimpleLevelContextType
from _nsgroup import SpecifierPayloadType_ # {urn:X-fsgim:fsgim}SpecifierPayloadType
from _nsgroup import PowerCurve_ # {urn:X-fsgim:fsgim}PowerCurve
from _nsgroup import PowerRatings_ # {urn:X-fsgim:fsgim}PowerRatings
from _nsgroup import ConnectionTypeEnumeration # {urn:X-fsgim:fsgim}ConnectionTypeEnumeration
from _nsgroup import DRCS_ChaSt_ING # {urn:X-fsgim:fsgim}DRCS.ChaSt.ING
from _nsgroup import DRCT_DERtyp_ING # {urn:X-fsgim:fsgim}DRCT.DERtyp.ING
from _nsgroup import GeneratorOperationStatusEnumeration # {urn:X-fsgim:fsgim}GeneratorOperationStatusEnumeration
from _nsgroup import MMXN_range_CMV # {urn:X-fsgim:fsgim}MMXN.range.CMV
from _nsgroup import ScheduleOperatingModeKind # {urn:X-fsgim:fsgim}ScheduleOperatingModeKind
from _nsgroup import SequenceDirectionEnumeration # {urn:X-fsgim:fsgim}SequenceDirectionEnumeration
from _nsgroup import X_ctlModel_X # {urn:X-fsgim:fsgim}X.ctlModel.X
from _nsgroup import X_occPer_SCR # {urn:X-fsgim:fsgim}X.occPer.SCR
from _nsgroup import X_q_X # {urn:X-fsgim:fsgim}X.q.X
from _nsgroup import X_rmpTyp_X # {urn:X-fsgim:fsgim}X.rmpTyp.X
from _nsgroup import X_valEq_X # {urn:X-fsgim:fsgim}X.valEq.X
from _nsgroup import CurrencyKind # {urn:X-fsgim:fsgim}CurrencyKind
from _nsgroup import MonthType # {urn:X-fsgim:fsgim}MonthType
from _nsgroup import QualityOfReading # {urn:X-fsgim:fsgim}QualityOfReading
from _nsgroup import SiScaleCodeType # {urn:X-fsgim:fsgim}SiScaleCodeType
from _nsgroup import UnitSymbolKind # {urn:X-fsgim:fsgim}UnitSymbolKind
from _nsgroup import WeekdayType # {urn:X-fsgim:fsgim}WeekdayType
from _nsgroup import GlobalID # {urn:X-fsgim:fsgim}GlobalID
from _nsgroup import ConnectionPointState # {urn:X-fsgim:fsgim}ConnectionPointState
from _nsgroup import EnergyRouter_ # {urn:X-fsgim:fsgim}EnergyRouter
from _nsgroup import ArrayOfTerms_ # {urn:X-fsgim:fsgim}ArrayOfTerms
from _nsgroup import BaseTermType_ # {urn:X-fsgim:fsgim}BaseTermType
from _nsgroup import MarketContextNameType_ # {urn:X-fsgim:fsgim}MarketContextNameType
from _nsgroup import NonStandardTermsHandlingType # {urn:X-fsgim:fsgim}NonStandardTermsHandlingType
from _nsgroup import StandardTermsSetType_ # {urn:X-fsgim:fsgim}StandardTermsSetType
from _nsgroup import StandardTermsType_ # {urn:X-fsgim:fsgim}StandardTermsType
from _nsgroup import ItemBaseType_ # {urn:X-fsgim:fsgim}ItemBaseType
from _nsgroup import Measurement_ # {urn:X-fsgim:fsgim}Measurement
from _nsgroup import AggregationProperties_ # {urn:X-fsgim:fsgim}AggregationProperties
from _nsgroup import Compass16 # {urn:X-fsgim:fsgim}Compass16
from _nsgroup import Compass4 # {urn:X-fsgim:fsgim}Compass4
from _nsgroup import Compass8 # {urn:X-fsgim:fsgim}Compass8
from _nsgroup import ForecastChangeIndicator # {urn:X-fsgim:fsgim}ForecastChangeIndicator
from _nsgroup import Growth # {urn:X-fsgim:fsgim}Growth
from _nsgroup import IntensityChange # {urn:X-fsgim:fsgim}IntensityChange
from _nsgroup import PastTendency # {urn:X-fsgim:fsgim}PastTendency
from _nsgroup import PercentageRange_ # {urn:X-fsgim:fsgim}PercentageRange
from _nsgroup import WeatherDescriptor # {urn:X-fsgim:fsgim}WeatherDescriptor
from _nsgroup import WeatherIntensity # {urn:X-fsgim:fsgim}WeatherIntensity
from _nsgroup import WeatherModifier_ # {urn:X-fsgim:fsgim}WeatherModifier
from _nsgroup import WeatherProximity # {urn:X-fsgim:fsgim}WeatherProximity
from _nsgroup import WxCode_ # {urn:X-fsgim:fsgim}WxCode
from _nsgroup import ReportProcess_ # {urn:X-fsgim:fsgim}ReportProcess
from _nsgroup import ArrayOfRampSegments_ # {urn:X-fsgim:fsgim}ArrayOfRampSegments
from _nsgroup import OfferSegmentType_ # {urn:X-fsgim:fsgim}OfferSegmentType
from _nsgroup import ResourceTypeEnumeratedType # {urn:X-fsgim:fsgim}ResourceTypeEnumeratedType
from _nsgroup import ResourceTypeType_ # {urn:X-fsgim:fsgim}ResourceTypeType
from _nsgroup import ObservationCollection_ # {urn:X-fsgim:fsgim}ObservationCollection
from _nsgroup import AbstractMeasure_ # {urn:X-fsgim:fsgim}AbstractMeasure
from _nsgroup import Bearing_ # {urn:X-fsgim:fsgim}Bearing
from _nsgroup import Percentage_ # {urn:X-fsgim:fsgim}Percentage
from _nsgroup import ExtentOf_ # {urn:X-fsgim:fsgim}ExtentOf
from _nsgroup import LPL_ # {urn:X-fsgim:fsgim}LPL
from _nsgroup import CUG_ # {urn:X-fsgim:fsgim}CUG
from _nsgroup import ENG_ # {urn:X-fsgim:fsgim}ENG
from _nsgroup import ING_ # {urn:X-fsgim:fsgim}ING
from _nsgroup import ORG_ # {urn:X-fsgim:fsgim}ORG
from _nsgroup import SPG_ # {urn:X-fsgim:fsgim}SPG
from _nsgroup import APC_ # {urn:X-fsgim:fsgim}APC
from _nsgroup import DPC_ # {urn:X-fsgim:fsgim}DPC
from _nsgroup import ENC_ # {urn:X-fsgim:fsgim}ENC
from _nsgroup import SPC_ # {urn:X-fsgim:fsgim}SPC
from _nsgroup import BCR_ # {urn:X-fsgim:fsgim}BCR
from _nsgroup import ENS_ # {urn:X-fsgim:fsgim}ENS
from _nsgroup import INS_ # {urn:X-fsgim:fsgim}INS
from _nsgroup import SPS_ # {urn:X-fsgim:fsgim}SPS
from _nsgroup import DEL_ # {urn:X-fsgim:fsgim}DEL
from _nsgroup import HarmonicMeasurandCDC_ # {urn:X-fsgim:fsgim}HarmonicMeasurandCDC
from _nsgroup import RangeDeadbandCDC_ # {urn:X-fsgim:fsgim}RangeDeadbandCDC
from _nsgroup import WYE_ # {urn:X-fsgim:fsgim}WYE
from _nsgroup import ASG_ # {urn:X-fsgim:fsgim}ASG
from _nsgroup import CSG_ # {urn:X-fsgim:fsgim}CSG
from _nsgroup import DomainLN_ # {urn:X-fsgim:fsgim}DomainLN
from _nsgroup import ChargeStatusENS_ # {urn:X-fsgim:fsgim}ChargeStatusENS
from _nsgroup import ConnectionTypeENS_ # {urn:X-fsgim:fsgim}ConnectionTypeENS
from _nsgroup import GeneratorOperationStatusENS_ # {urn:X-fsgim:fsgim}GeneratorOperationStatusENS
from _nsgroup import SCR_ # {urn:X-fsgim:fsgim}SCR
from _nsgroup import SequenceDirectionENS_ # {urn:X-fsgim:fsgim}SequenceDirectionENS
from _nsgroup import DQ_Element_ # {urn:X-fsgim:fsgim}DQ_Element
from _nsgroup import DQ_EvaluationMethodTypeCode # {urn:X-fsgim:fsgim}DQ_EvaluationMethodTypeCode
from _nsgroup import DirectPosition_ # {urn:X-fsgim:fsgim}DirectPosition
from _nsgroup import GM_Envelope_ # {urn:X-fsgim:fsgim}GM_Envelope
from _nsgroup import MD_Metadata_ # {urn:X-fsgim:fsgim}MD_Metadata
from _nsgroup import EnumDA_ # {urn:X-fsgim:fsgim}EnumDA
from _nsgroup import DpStatusKind # {urn:X-fsgim:fsgim}DpStatusKind
from _nsgroup import MD_Identifier_ # {urn:X-fsgim:fsgim}MD_Identifier
from _nsgroup import AnalogueValue_ # {urn:X-fsgim:fsgim}AnalogueValue
from _nsgroup import DetailQual_ # {urn:X-fsgim:fsgim}DetailQual
from _nsgroup import Originator_ # {urn:X-fsgim:fsgim}Originator
from _nsgroup import Point_ # {urn:X-fsgim:fsgim}Point
from _nsgroup import PulseConfig_ # {urn:X-fsgim:fsgim}PulseConfig
from _nsgroup import Quality_ # {urn:X-fsgim:fsgim}Quality
from _nsgroup import RangeConfig_ # {urn:X-fsgim:fsgim}RangeConfig
from _nsgroup import ScaledValueConfig_ # {urn:X-fsgim:fsgim}ScaledValueConfig
from _nsgroup import SourceKind # {urn:X-fsgim:fsgim}SourceKind
from _nsgroup import Unit_ # {urn:X-fsgim:fsgim}Unit
from _nsgroup import ValidityKind # {urn:X-fsgim:fsgim}ValidityKind
from _nsgroup import Vector_ # {urn:X-fsgim:fsgim}Vector
from _nsgroup import AngleReferenceKind # {urn:X-fsgim:fsgim}AngleReferenceKind
from _nsgroup import ControlOutputKind # {urn:X-fsgim:fsgim}ControlOutputKind
from _nsgroup import CtlModelKind # {urn:X-fsgim:fsgim}CtlModelKind
from _nsgroup import HvReferenceKind # {urn:X-fsgim:fsgim}HvReferenceKind
from _nsgroup import OriginatorCategoryKind # {urn:X-fsgim:fsgim}OriginatorCategoryKind
from _nsgroup import RangeKind # {urn:X-fsgim:fsgim}RangeKind
from _nsgroup import SIUnitKind # {urn:X-fsgim:fsgim}SIUnitKind
from _nsgroup import ObjectReference_ # {urn:X-fsgim:fsgim}ObjectReference
from _nsgroup import LanguageCode # {urn:X-fsgim:fsgim}LanguageCode
from _nsgroup import MD_ScopeCode # {urn:X-fsgim:fsgim}MD_ScopeCode
from _nsgroup import MD_CharacterSetCode # {urn:X-fsgim:fsgim}MD_CharacterSetCode
from _nsgroup import CI_Address_ # {urn:X-fsgim:fsgim}CI_Address
from _nsgroup import CI_Citation_ # {urn:X-fsgim:fsgim}CI_Citation
from _nsgroup import CI_Contact_ # {urn:X-fsgim:fsgim}CI_Contact
from _nsgroup import CI_OnLineFunctionCode # {urn:X-fsgim:fsgim}CI_OnLineFunctionCode
from _nsgroup import CI_OnlineResource_ # {urn:X-fsgim:fsgim}CI_OnlineResource
from _nsgroup import CI_PresentationFormCode # {urn:X-fsgim:fsgim}CI_PresentationFormCode
from _nsgroup import CI_ResponsibleParty_ # {urn:X-fsgim:fsgim}CI_ResponsibleParty
from _nsgroup import CI_RoleCode # {urn:X-fsgim:fsgim}CI_RoleCode
from _nsgroup import CI_Series_ # {urn:X-fsgim:fsgim}CI_Series
from _nsgroup import CI_Telephone_ # {urn:X-fsgim:fsgim}CI_Telephone
from _nsgroup import PT_Locale_ # {urn:X-fsgim:fsgim}PT_Locale
from _nsgroup import CountryCode # {urn:X-fsgim:fsgim}CountryCode
from _nsgroup import EMIntervalDataRestrictions_ # {urn:X-fsgim:fsgim}EMIntervalDataRestrictions
from _nsgroup import ServiceSupplierData_ # {urn:X-fsgim:fsgim}ServiceSupplierData
from _nsgroup import Aggregation_ # {urn:X-fsgim:fsgim}Aggregation
from _nsgroup import RuleSet_ # {urn:X-fsgim:fsgim}RuleSet
from _nsgroup import EmixInterfaceType_ # {urn:X-fsgim:fsgim}EmixInterfaceType
from _nsgroup import OptionTypeEnumeratedType_ # {urn:X-fsgim:fsgim}OptionTypeEnumeratedType
from _nsgroup import PriceMultiplierType_ # {urn:X-fsgim:fsgim}PriceMultiplierType
from _nsgroup import PriceRelativeType_ # {urn:X-fsgim:fsgim}PriceRelativeType
from _nsgroup import PriceType_ # {urn:X-fsgim:fsgim}PriceType
from _nsgroup import Customer_ # {urn:X-fsgim:fsgim}Customer
from _nsgroup import CustomerAuthorisation_ # {urn:X-fsgim:fsgim}CustomerAuthorisation
from _nsgroup import ElectricPowerQualitySummary_ # {urn:X-fsgim:fsgim}ElectricPowerQualitySummary
from _nsgroup import IntervalBlock_ # {urn:X-fsgim:fsgim}IntervalBlock
from _nsgroup import IntervalReading_ # {urn:X-fsgim:fsgim}IntervalReading
from _nsgroup import MeterReading_ # {urn:X-fsgim:fsgim}MeterReading
from _nsgroup import Reading_ # {urn:X-fsgim:fsgim}Reading
from _nsgroup import UsagePoint_ # {urn:X-fsgim:fsgim}UsagePoint
from _nsgroup import UsageSummary_ # {urn:X-fsgim:fsgim}UsageSummary
from _nsgroup import LocalDateTimeInterval_ # {urn:X-fsgim:fsgim}LocalDateTimeInterval
from _nsgroup import LocalTimeParameters_ # {urn:X-fsgim:fsgim}LocalTimeParameters
from _nsgroup import UTCDateTimeInterval_ # {urn:X-fsgim:fsgim}UTCDateTimeInterval
from _nsgroup import IntervalType_ # {urn:X-fsgim:fsgim}IntervalType
from _nsgroup import Randomization_ # {urn:X-fsgim:fsgim}Randomization
from _nsgroup import RelationLink_ # {urn:X-fsgim:fsgim}RelationLink
from _nsgroup import FSGIMPayloadBaseType_ # {urn:X-fsgim:fsgim}FSGIMPayloadBaseType
from _nsgroup import Circuit_ # {urn:X-fsgim:fsgim}Circuit
from _nsgroup import ComponentElement_ # {urn:X-fsgim:fsgim}ComponentElement
from _nsgroup import Device_ # {urn:X-fsgim:fsgim}Device
from _nsgroup import Irradiance_ # {urn:X-fsgim:fsgim}Irradiance
from _nsgroup import RelativeHumidity_ # {urn:X-fsgim:fsgim}RelativeHumidity
from _nsgroup import MeasurementProtocolType # {urn:X-fsgim:fsgim}MeasurementProtocolType
from _nsgroup import PowerQualityWarrantType_ # {urn:X-fsgim:fsgim}PowerQualityWarrantType
from _nsgroup import QualityTypeType # {urn:X-fsgim:fsgim}QualityTypeType
from _nsgroup import ApplicationSpecificContextBaseType_ # {urn:X-fsgim:fsgim}ApplicationSpecificContextBaseType
from _nsgroup import ApplicationSpecificPayloadBaseType_ # {urn:X-fsgim:fsgim}ApplicationSpecificPayloadBaseType
from _nsgroup import EiEventSignalType_ # {urn:X-fsgim:fsgim}EiEventSignalType
from _nsgroup import EiTargetType_ # {urn:X-fsgim:fsgim}EiTargetType
from _nsgroup import EventDescriptorType_ # {urn:X-fsgim:fsgim}EventDescriptorType
from _nsgroup import EventStatusType # {urn:X-fsgim:fsgim}EventStatusType
from _nsgroup import FSGIMEventSignalType_ # {urn:X-fsgim:fsgim}FSGIMEventSignalType
from _nsgroup import PayloadApplicationSpecificType_ # {urn:X-fsgim:fsgim}PayloadApplicationSpecificType
from _nsgroup import PayloadEmixType_ # {urn:X-fsgim:fsgim}PayloadEmixType
from _nsgroup import PayloadFloatType_ # {urn:X-fsgim:fsgim}PayloadFloatType
from _nsgroup import PayloadLevelType_ # {urn:X-fsgim:fsgim}PayloadLevelType
from _nsgroup import PayloadPriceMultiplierType_ # {urn:X-fsgim:fsgim}PayloadPriceMultiplierType
from _nsgroup import PayloadPriceRelativeType_ # {urn:X-fsgim:fsgim}PayloadPriceRelativeType
from _nsgroup import PayloadPriceType_ # {urn:X-fsgim:fsgim}PayloadPriceType
from _nsgroup import PayloadProductType_ # {urn:X-fsgim:fsgim}PayloadProductType
from _nsgroup import PayloadQuantityType_ # {urn:X-fsgim:fsgim}PayloadQuantityType
from _nsgroup import ReadingTypeType # {urn:X-fsgim:fsgim}ReadingTypeType
from _nsgroup import SignalTypeType # {urn:X-fsgim:fsgim}SignalTypeType
from _nsgroup import DERMeasurement_ # {urn:X-fsgim:fsgim}DERMeasurement
from _nsgroup import DERComplexOutputRamping_ # {urn:X-fsgim:fsgim}DERComplexOutputRamping
from _nsgroup import DERCostParameters_ # {urn:X-fsgim:fsgim}DERCostParameters
from _nsgroup import DERDeviceControllerCharacteristics_ # {urn:X-fsgim:fsgim}DERDeviceControllerCharacteristics
from _nsgroup import DERGeneratorRatings_ # {urn:X-fsgim:fsgim}DERGeneratorRatings
from _nsgroup import DEROperationalModeControls_ # {urn:X-fsgim:fsgim}DEROperationalModeControls
from _nsgroup import DERThermalStorage_ # {urn:X-fsgim:fsgim}DERThermalStorage
from _nsgroup import DERUnitControlActions_ # {urn:X-fsgim:fsgim}DERUnitControlActions
from _nsgroup import DERUnitGenerator_ # {urn:X-fsgim:fsgim}DERUnitGenerator
from _nsgroup import DERUnitStatus_ # {urn:X-fsgim:fsgim}DERUnitStatus
from _nsgroup import BidirectionalCombiner_ # {urn:X-fsgim:fsgim}BidirectionalCombiner
from _nsgroup import GridTransferSwitch_ # {urn:X-fsgim:fsgim}GridTransferSwitch
from _nsgroup import RouterConnectionPoint_ # {urn:X-fsgim:fsgim}RouterConnectionPoint
from _nsgroup import TransferSwitch_ # {urn:X-fsgim:fsgim}TransferSwitch
from _nsgroup import UnidirectionalCombiner_ # {urn:X-fsgim:fsgim}UnidirectionalCombiner
from _nsgroup import AvailabilityScheduleType_ # {urn:X-fsgim:fsgim}AvailabilityScheduleType
from _nsgroup import MarketGranularityType_ # {urn:X-fsgim:fsgim}MarketGranularityType
from _nsgroup import MaximumConsecutiveDurationsType_ # {urn:X-fsgim:fsgim}MaximumConsecutiveDurationsType
from _nsgroup import MaximumInvocationsPerDurationType_ # {urn:X-fsgim:fsgim}MaximumInvocationsPerDurationType
from _nsgroup import MaximumNotificationDurationType_ # {urn:X-fsgim:fsgim}MaximumNotificationDurationType
from _nsgroup import MaximumResponseDurationType_ # {urn:X-fsgim:fsgim}MaximumResponseDurationType
from _nsgroup import MaximumRunDurationType_ # {urn:X-fsgim:fsgim}MaximumRunDurationType
from _nsgroup import MinimumDurationBetweenInvocationsType_ # {urn:X-fsgim:fsgim}MinimumDurationBetweenInvocationsType
from _nsgroup import MinimumEconomicRequirementType_ # {urn:X-fsgim:fsgim}MinimumEconomicRequirementType
from _nsgroup import MinimumNotificationDurationType_ # {urn:X-fsgim:fsgim}MinimumNotificationDurationType
from _nsgroup import MinimumRecoveryDurationType_ # {urn:X-fsgim:fsgim}MinimumRecoveryDurationType
from _nsgroup import MinimumRemunerationRateType_ # {urn:X-fsgim:fsgim}MinimumRemunerationRateType
from _nsgroup import MinimumResponseDurationType_ # {urn:X-fsgim:fsgim}MinimumResponseDurationType
from _nsgroup import MinimumRunDurationType_ # {urn:X-fsgim:fsgim}MinimumRunDurationType
from _nsgroup import MinimumStartsPerDurationType_ # {urn:X-fsgim:fsgim}MinimumStartsPerDurationType
from _nsgroup import NotificationScheduleType_ # {urn:X-fsgim:fsgim}NotificationScheduleType
from _nsgroup import RequiredStartupRemunerationType_ # {urn:X-fsgim:fsgim}RequiredStartupRemunerationType
from _nsgroup import ResponseTimeType_ # {urn:X-fsgim:fsgim}ResponseTimeType
from _nsgroup import UnavailabilityScheduleType_ # {urn:X-fsgim:fsgim}UnavailabilityScheduleType
from _nsgroup import MeasurementMetadataType_ # {urn:X-fsgim:fsgim}MeasurementMetadataType
from _nsgroup import MeasurementQuantityRestrictions_ # {urn:X-fsgim:fsgim}MeasurementQuantityRestrictions
from _nsgroup import MeasurementSet_ # {urn:X-fsgim:fsgim}MeasurementSet
from _nsgroup import WindDirection_ # {urn:X-fsgim:fsgim}WindDirection
from _nsgroup import AbstractFeature_ # {urn:X-fsgim:fsgim}AbstractFeature
from _nsgroup import OfferCurveType_ # {urn:X-fsgim:fsgim}OfferCurveType
from _nsgroup import PowerResponseType_ # {urn:X-fsgim:fsgim}PowerResponseType
from _nsgroup import Observation_ # {urn:X-fsgim:fsgim}Observation
from _nsgroup import Angle_ # {urn:X-fsgim:fsgim}Angle
from _nsgroup import Distance_ # {urn:X-fsgim:fsgim}Distance
from _nsgroup import Luminance_ # {urn:X-fsgim:fsgim}Luminance
from _nsgroup import Pressure_ # {urn:X-fsgim:fsgim}Pressure
from _nsgroup import Speed_ # {urn:X-fsgim:fsgim}Speed
from _nsgroup import Temperature_ # {urn:X-fsgim:fsgim}Temperature
from _nsgroup import ENCBehaviourMode_ # {urn:X-fsgim:fsgim}ENCBehaviourMode
from _nsgroup import ENGCalcIntervalType_ # {urn:X-fsgim:fsgim}ENGCalcIntervalType
from _nsgroup import ENGCalcMethod_ # {urn:X-fsgim:fsgim}ENGCalcMethod
from _nsgroup import ENGCalcMode_ # {urn:X-fsgim:fsgim}ENGCalcMode
from _nsgroup import ENGPfSign_ # {urn:X-fsgim:fsgim}ENGPfSign
from _nsgroup import ENGSTotalCalcMethod_ # {urn:X-fsgim:fsgim}ENGSTotalCalcMethod
from _nsgroup import ENSAdjustment_ # {urn:X-fsgim:fsgim}ENSAdjustment
from _nsgroup import ENSBehaviourMode_ # {urn:X-fsgim:fsgim}ENSBehaviourMode
from _nsgroup import ENSHealth_ # {urn:X-fsgim:fsgim}ENSHealth
from _nsgroup import SPCTransient_ # {urn:X-fsgim:fsgim}SPCTransient
from _nsgroup import SPSTransient_ # {urn:X-fsgim:fsgim}SPSTransient
from _nsgroup import CMV_ # {urn:X-fsgim:fsgim}CMV
from _nsgroup import HMV_ # {urn:X-fsgim:fsgim}HMV
from _nsgroup import MV_ # {urn:X-fsgim:fsgim}MV
from _nsgroup import LLN0_ # {urn:X-fsgim:fsgim}LLN0
from _nsgroup import LPHD_ # {urn:X-fsgim:fsgim}LPHD
from _nsgroup import EM_ # {urn:X-fsgim:fsgim}EM
from _nsgroup import EMGenerationType_ # {urn:X-fsgim:fsgim}EMGenerationType
from _nsgroup import EMIntervalData_ # {urn:X-fsgim:fsgim}EMIntervalData
from _nsgroup import EMPowerResponseType_ # {urn:X-fsgim:fsgim}EMPowerResponseType
from _nsgroup import EMUsagePoint_ # {urn:X-fsgim:fsgim}EMUsagePoint
from _nsgroup import IntervalDataContainerRestrictions_ # {urn:X-fsgim:fsgim}IntervalDataContainerRestrictions
from _nsgroup import Collection_ # {urn:X-fsgim:fsgim}Collection
from _nsgroup import ServiceAreaType_ # {urn:X-fsgim:fsgim}ServiceAreaType
from _nsgroup import Meter_ # {urn:X-fsgim:fsgim}Meter
from _nsgroup import AggregatedPnodeType_ # {urn:X-fsgim:fsgim}AggregatedPnodeType
from _nsgroup import EndDeviceAssetType_ # {urn:X-fsgim:fsgim}EndDeviceAssetType
from _nsgroup import MeterAssetType_ # {urn:X-fsgim:fsgim}MeterAssetType
from _nsgroup import PnodeType_ # {urn:X-fsgim:fsgim}PnodeType
from _nsgroup import ServiceDeliveryPointType_ # {urn:X-fsgim:fsgim}ServiceDeliveryPointType
from _nsgroup import ServiceLocationType_ # {urn:X-fsgim:fsgim}ServiceLocationType
from _nsgroup import TransportInterfaceType_ # {urn:X-fsgim:fsgim}TransportInterfaceType
from _nsgroup import Generator_ # {urn:X-fsgim:fsgim}Generator
from _nsgroup import GluonTypeRestrictions_ # {urn:X-fsgim:fsgim}GluonTypeRestrictions
from _nsgroup import FSGIMPayloadFloatType_ # {urn:X-fsgim:fsgim}FSGIMPayloadFloatType
from _nsgroup import FSGIMPayloadLevelType_ # {urn:X-fsgim:fsgim}FSGIMPayloadLevelType
from _nsgroup import FSGIMPayloadQuantityType_ # {urn:X-fsgim:fsgim}FSGIMPayloadQuantityType
from _nsgroup import Load_ # {urn:X-fsgim:fsgim}Load
from _nsgroup import GridCircuit_ # {urn:X-fsgim:fsgim}GridCircuit
from _nsgroup import FSGIMWeatherArea_ # {urn:X-fsgim:fsgim}FSGIMWeatherArea
from _nsgroup import FSGIMWeatherBase_ # {urn:X-fsgim:fsgim}FSGIMWeatherBase
from _nsgroup import FSGIMWeatherForecast_ # {urn:X-fsgim:fsgim}FSGIMWeatherForecast
from _nsgroup import FSGIMWeatherObservation_ # {urn:X-fsgim:fsgim}FSGIMWeatherObservation
from _nsgroup import FSGIMWeatherReport_ # {urn:X-fsgim:fsgim}FSGIMWeatherReport
from _nsgroup import FSGIMWeatherTrend_ # {urn:X-fsgim:fsgim}FSGIMWeatherTrend
from _nsgroup import AdjustedFullDRDemandAggregationRestrictions_ # {urn:X-fsgim:fsgim}AdjustedFullDRDemandAggregationRestrictions
from _nsgroup import AdjustedFullDRSupplyAggregationRestrictions_ # {urn:X-fsgim:fsgim}AdjustedFullDRSupplyAggregationRestrictions
from _nsgroup import AdjustedNoDRDemandAggregationRestrictions_ # {urn:X-fsgim:fsgim}AdjustedNoDRDemandAggregationRestrictions
from _nsgroup import AdjustedNoDRSupplyAggregationRestrictions_ # {urn:X-fsgim:fsgim}AdjustedNoDRSupplyAggregationRestrictions
from _nsgroup import DemandAggregationRestrictions_ # {urn:X-fsgim:fsgim}DemandAggregationRestrictions
from _nsgroup import ElectricalEnergyStoredAggregationRestrictions_ # {urn:X-fsgim:fsgim}ElectricalEnergyStoredAggregationRestrictions
from _nsgroup import EmissionsGeneratedAggregationRestrictions_ # {urn:X-fsgim:fsgim}EmissionsGeneratedAggregationRestrictions
from _nsgroup import EmissionsGenerationRateAggregationRestrictions_ # {urn:X-fsgim:fsgim}EmissionsGenerationRateAggregationRestrictions
from _nsgroup import EnergyConsumedAggregationRestrictions_ # {urn:X-fsgim:fsgim}EnergyConsumedAggregationRestrictions
from _nsgroup import EnergySuppliedAggregationRestrictions_ # {urn:X-fsgim:fsgim}EnergySuppliedAggregationRestrictions
from _nsgroup import NetDemandAggregationRestrictions_ # {urn:X-fsgim:fsgim}NetDemandAggregationRestrictions
from _nsgroup import NetEnergyConsumedAggregationRestrictions_ # {urn:X-fsgim:fsgim}NetEnergyConsumedAggregationRestrictions
from _nsgroup import SupplyAggregationRestrictions_ # {urn:X-fsgim:fsgim}SupplyAggregationRestrictions
from _nsgroup import ThermalEnergyStoredAggregationRestrictions_ # {urn:X-fsgim:fsgim}ThermalEnergyStoredAggregationRestrictions
from _nsgroup import AbstractPhenomenon_ # {urn:X-fsgim:fsgim}AbstractPhenomenon
from _nsgroup import WxCondition_ # {urn:X-fsgim:fsgim}WxCondition
from _nsgroup import PowerItemType_ # {urn:X-fsgim:fsgim}PowerItemType
from _nsgroup import PowerMeasurementsSetRestrictions_ # {urn:X-fsgim:fsgim}PowerMeasurementsSetRestrictions
from _nsgroup import EnergyItemType_ # {urn:X-fsgim:fsgim}EnergyItemType
from _nsgroup import EnergyMeasurementsSetRestrictions_ # {urn:X-fsgim:fsgim}EnergyMeasurementsSetRestrictions
from _nsgroup import ThermalEnergyMeasurementsSetRestrictions_ # {urn:X-fsgim:fsgim}ThermalEnergyMeasurementsSetRestrictions
from _nsgroup import EmissionsItemType_ # {urn:X-fsgim:fsgim}EmissionsItemType
from _nsgroup import EmissionsMeasurementsSetRestrictions_ # {urn:X-fsgim:fsgim}EmissionsMeasurementsSetRestrictions
from _nsgroup import MeasurementQuantity_ # {urn:X-fsgim:fsgim}MeasurementQuantity
from _nsgroup import AirTemperature_ # {urn:X-fsgim:fsgim}AirTemperature
from _nsgroup import HorizontalDistance_ # {urn:X-fsgim:fsgim}HorizontalDistance
from _nsgroup import VerticalDistance_ # {urn:X-fsgim:fsgim}VerticalDistance
from _nsgroup import WindGust_ # {urn:X-fsgim:fsgim}WindGust
from _nsgroup import WindSpeed_ # {urn:X-fsgim:fsgim}WindSpeed
from _nsgroup import LoadReductionType_ # {urn:X-fsgim:fsgim}LoadReductionType
from _nsgroup import EMLoadReductionType_ # {urn:X-fsgim:fsgim}EMLoadReductionType
from _nsgroup import IntervalDataContainer_ # {urn:X-fsgim:fsgim}IntervalDataContainer
from _nsgroup import AllResourcesInEMDomain_ # {urn:X-fsgim:fsgim}AllResourcesInEMDomain
from _nsgroup import FilteredCollection_ # {urn:X-fsgim:fsgim}FilteredCollection
from _nsgroup import ElectricMeter_ # {urn:X-fsgim:fsgim}ElectricMeter
from _nsgroup import EmissionsMeter_ # {urn:X-fsgim:fsgim}EmissionsMeter
from _nsgroup import DispatchableGenerator_ # {urn:X-fsgim:fsgim}DispatchableGenerator
from _nsgroup import GluonType_ # {urn:X-fsgim:fsgim}GluonType
from _nsgroup import CurtailableLoad_ # {urn:X-fsgim:fsgim}CurtailableLoad
from _nsgroup import FSGIMPrecipitation_ # {urn:X-fsgim:fsgim}FSGIMPrecipitation
from _nsgroup import AdjustedFullDRDemandAggregation_ # {urn:X-fsgim:fsgim}AdjustedFullDRDemandAggregation
from _nsgroup import AdjustedFullDRSupplyAggregation_ # {urn:X-fsgim:fsgim}AdjustedFullDRSupplyAggregation
from _nsgroup import AdjustedNoDRDemandAggregation_ # {urn:X-fsgim:fsgim}AdjustedNoDRDemandAggregation
from _nsgroup import AdjustedNoDRSupplyAggregation_ # {urn:X-fsgim:fsgim}AdjustedNoDRSupplyAggregation
from _nsgroup import DemandAggregation_ # {urn:X-fsgim:fsgim}DemandAggregation
from _nsgroup import ElectricalEnergyStoredAggregation_ # {urn:X-fsgim:fsgim}ElectricalEnergyStoredAggregation
from _nsgroup import EmissionsGeneratedAggregation_ # {urn:X-fsgim:fsgim}EmissionsGeneratedAggregation
from _nsgroup import EmissionsGenerationRateAggregation_ # {urn:X-fsgim:fsgim}EmissionsGenerationRateAggregation
from _nsgroup import EnergyConsumedAggregation_ # {urn:X-fsgim:fsgim}EnergyConsumedAggregation
from _nsgroup import EnergySuppliedAggregation_ # {urn:X-fsgim:fsgim}EnergySuppliedAggregation
from _nsgroup import NetDemandAggregation_ # {urn:X-fsgim:fsgim}NetDemandAggregation
from _nsgroup import NetEnergyConsumedAggregation_ # {urn:X-fsgim:fsgim}NetEnergyConsumedAggregation
from _nsgroup import SupplyAggregation_ # {urn:X-fsgim:fsgim}SupplyAggregation
from _nsgroup import ThermalEnergyStoredAggregation_ # {urn:X-fsgim:fsgim}ThermalEnergyStoredAggregation
from _nsgroup import PowerApparentType_ # {urn:X-fsgim:fsgim}PowerApparentType
from _nsgroup import PowerMeasurementsSet_ # {urn:X-fsgim:fsgim}PowerMeasurementsSet
from _nsgroup import PowerQuantityType_ # {urn:X-fsgim:fsgim}PowerQuantityType
from _nsgroup import PowerReactiveType_ # {urn:X-fsgim:fsgim}PowerReactiveType
from _nsgroup import PowerRealType_ # {urn:X-fsgim:fsgim}PowerRealType
from _nsgroup import PowerThermalType_ # {urn:X-fsgim:fsgim}PowerThermalType
from _nsgroup import CloudCondition_ # {urn:X-fsgim:fsgim}CloudCondition
from _nsgroup import EnergyApparentType_ # {urn:X-fsgim:fsgim}EnergyApparentType
from _nsgroup import EnergyMeasurementsSet_ # {urn:X-fsgim:fsgim}EnergyMeasurementsSet
from _nsgroup import EnergyQuantityType_ # {urn:X-fsgim:fsgim}EnergyQuantityType
from _nsgroup import EnergyReactiveType_ # {urn:X-fsgim:fsgim}EnergyReactiveType
from _nsgroup import EnergyRealType_ # {urn:X-fsgim:fsgim}EnergyRealType
from _nsgroup import EnergyThermalType_ # {urn:X-fsgim:fsgim}EnergyThermalType
from _nsgroup import ThermalEnergyMeasurementsSet_ # {urn:X-fsgim:fsgim}ThermalEnergyMeasurementsSet
from _nsgroup import EmissionsConcentrationType_ # {urn:X-fsgim:fsgim}EmissionsConcentrationType
from _nsgroup import EmissionsMassRateType_ # {urn:X-fsgim:fsgim}EmissionsMassRateType
from _nsgroup import EmissionsMassType_ # {urn:X-fsgim:fsgim}EmissionsMassType
from _nsgroup import EmissionsMeasurementsSet_ # {urn:X-fsgim:fsgim}EmissionsMeasurementsSet
from _nsgroup import EmissionsQuantityType_ # {urn:X-fsgim:fsgim}EmissionsQuantityType
from _nsgroup import EmissionsRateMeasurementsSet_ # {urn:X-fsgim:fsgim}EmissionsRateMeasurementsSet
from _nsgroup import CloudHeight_ # {urn:X-fsgim:fsgim}CloudHeight
from _nsgroup import Depth_ # {urn:X-fsgim:fsgim}Depth
from _nsgroup import HorizontalVisibilityDistance_ # {urn:X-fsgim:fsgim}HorizontalVisibilityDistance
from _nsgroup import VerticalVisibilityDistance_ # {urn:X-fsgim:fsgim}VerticalVisibilityDistance
from _nsgroup import Sequence_ # {urn:X-fsgim:fsgim}Sequence
from _nsgroup import EmixBaseType_ # {urn:X-fsgim:fsgim}EmixBaseType
from _nsgroup import PowerApparentQuantityRestrictions_ # {urn:X-fsgim:fsgim}PowerApparentQuantityRestrictions
from _nsgroup import PowerReactiveQuantityRestrictions_ # {urn:X-fsgim:fsgim}PowerReactiveQuantityRestrictions
from _nsgroup import PowerRealQuantityRestrictions_ # {urn:X-fsgim:fsgim}PowerRealQuantityRestrictions
from _nsgroup import PowerThermalQuantityRestrictions_ # {urn:X-fsgim:fsgim}PowerThermalQuantityRestrictions
from _nsgroup import EnergyApparentQuantityRestrictions_ # {urn:X-fsgim:fsgim}EnergyApparentQuantityRestrictions
from _nsgroup import EnergyReactiveQuantityRestrictions_ # {urn:X-fsgim:fsgim}EnergyReactiveQuantityRestrictions
from _nsgroup import StoreableEnergyQuantity_ # {urn:X-fsgim:fsgim}StoreableEnergyQuantity
from _nsgroup import EmissionsConcentrationQuantityRestrictions_ # {urn:X-fsgim:fsgim}EmissionsConcentrationQuantityRestrictions
from _nsgroup import EmissionsMassQuantityRestrictions_ # {urn:X-fsgim:fsgim}EmissionsMassQuantityRestrictions
from _nsgroup import EmissionsMassRateQuantityRestrictions_ # {urn:X-fsgim:fsgim}EmissionsMassRateQuantityRestrictions
from _nsgroup import ForecastSequence_ # {urn:X-fsgim:fsgim}ForecastSequence
from _nsgroup import DeliveryType_ # {urn:X-fsgim:fsgim}DeliveryType
from _nsgroup import EmixOptionType_ # {urn:X-fsgim:fsgim}EmixOptionType
from _nsgroup import ProductType_ # {urn:X-fsgim:fsgim}ProductType
from _nsgroup import PowerApparentQuantity_ # {urn:X-fsgim:fsgim}PowerApparentQuantity
from _nsgroup import PowerReactiveQuantity_ # {urn:X-fsgim:fsgim}PowerReactiveQuantity
from _nsgroup import PowerRealQuantity_ # {urn:X-fsgim:fsgim}PowerRealQuantity
from _nsgroup import PowerThermalQuantity_ # {urn:X-fsgim:fsgim}PowerThermalQuantity
from _nsgroup import EnergyApparentQuantity_ # {urn:X-fsgim:fsgim}EnergyApparentQuantity
from _nsgroup import EnergyReactiveQuantity_ # {urn:X-fsgim:fsgim}EnergyReactiveQuantity
from _nsgroup import EnergyRealQuantityRestrictions_ # {urn:X-fsgim:fsgim}EnergyRealQuantityRestrictions
from _nsgroup import EnergyThermalQuantityRestrictions_ # {urn:X-fsgim:fsgim}EnergyThermalQuantityRestrictions
from _nsgroup import EmissionsConcentrationQuantity_ # {urn:X-fsgim:fsgim}EmissionsConcentrationQuantity
from _nsgroup import EmissionsMassQuantity_ # {urn:X-fsgim:fsgim}EmissionsMassQuantity
from _nsgroup import EmissionsMassRateQuantity_ # {urn:X-fsgim:fsgim}EmissionsMassRateQuantity
from _nsgroup import EnergyRealQuantity_ # {urn:X-fsgim:fsgim}EnergyRealQuantity
from _nsgroup import EnergyThermalQuantity_ # {urn:X-fsgim:fsgim}EnergyThermalQuantity
